### ISSUE TITLE
Merging new features in this repository

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#32]
Hi Ryan 👋 

I'd like to make some changes and add some features in this project. I know we're using this as a dependency in symfony/symfony-docs repository, so I'm proposing to pin the version used in Symfony Docs (see https://github.com/symfony/symfony-docs/pull/15018) to a specific commit, which is the last merge you did in this repository (https://github.com/weaverryan/docs-builder/commit/e388a6f8cd7a98c34cdc913d18adc9e92ef73441).

Do you think it's safe to merge things after that change in Symfony Docs is merged? Or do you prefer to do things differently? Thanks!

**Comment by OskarStark** [comment]
Instead we can safely release a 0.1 or a beta release?

**Comment by weaverryan** [comment]
I just tagged 0.12.0. I actually had this as a draft commit from October... I guess I forgot actually finish it. Anyways, I've been tagging along the way - and we should keep doing that. So we can ping at 0.12.0 for safety.

> Do you think it's safe to merge things after that change in Symfony Docs is merged?

This sounds great. I'll check your PR's right now!

**Comment by javiereguiluz** [comment]
Thanks for tagging! Updated the symfony-docs feature.
