### ISSUE TITLE
Issue when parsing code blocks inside list items

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#38]
In this article --> https://raw.githubusercontent.com/EasyCorp/EasyAdminBundle/master/doc/upgrade.rst we have this:

```rst
Removed Features
----------------

EasyAdmin 3 removes some features of the previous versions which are no longer
considered useful:

* The ``design.brand_color`` config option has been removed because you can't
  customize the backend design by changing just this value. If you still want to
  do that, use the following code in your dashboard class::

      class DashboardController extends AbstractDashboardController
      {
          // ...

          public function configureAssets(): Assets
          {
              return Assets::new()
                  // ...
                  ->addHtmlContentToHead('<style>:root { --color-primary: #123456; }</style>');
          }
      }

* The ``default: true`` option to set the default backend page has been removed.
  Use the :doc:`dashboard </dashboards>` index as the default page or redirect
  to the desired page inside the dashboard controller action.
```

In the current symfony.com it works OK:

![image](https://user-images.githubusercontent.com/73419/109685770-e4874500-7b81-11eb-82ee-c3cca473fae8.png)

But the new parser doesn't understand it:

![image](https://user-images.githubusercontent.com/73419/109685807-ecdf8000-7b81-11eb-9868-dc935f1efa97.png)

We might consider this _"won't fix because it's too edgy"_ and then rewrite the original RST content.

**Comment by wouterj** [comment]
Unfortunately, this is a lot bigger than just the literal blocks. The current rst parser *only* parses inline markup (strong, emphasis, etc) in the contents of a list. This means that any markup that is not inline (or "span" as they call it in rst parser) is broken, e.g:

```rst
* list item

  .. note::

      This is a note
```

We're also using these markups in some occasions of the Symfony docs, so this is a bit of a blocker.

**Comment by nikophil** [comment]
isn't that related?
https://github.com/doctrine/rst-parser/pull/86

**Comment by wouterj** [comment]
@nikophil yes it is. Thanks for mentioning it!

My first expectation was that the rst parser doesn't allow parsing nested block elements, but I just found fragment parsing in the table. So I hope this is now easier to fix, by also parsing the fragment of the list item. I'll see if I can manage creating a PR here :)

**Comment by javiereguiluz** [comment]
Closing as fixed by https://github.com/doctrine/rst-parser/pull/138

**Comment by wouterj** [comment]
@javiereguiluz that PR was about definition lists, not normal lists. I'll make a PR for normal lists (fixing this issue) later today
