### ISSUE TITLE
Issue with <code> elements in headings

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#45]
This file: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/dashboard.rst has things like these:

```rst
The ``Admin`` list block
------------------------

Configuring the ``Admin`` list
------------------------------

Using the ``Admin`` service declaration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

These are wrongly processed in the TOC, which shows the links like this:

![image](https://user-images.githubusercontent.com/73419/109800848-01715600-7c1e-11eb-984f-bbd563da4c20.png)

The contents of the heading are correctly displayed, but the "weird alphanumeric string" leaks to the permalink too:

![image](https://user-images.githubusercontent.com/73419/109801128-5745fe00-7c1e-11eb-95cb-3127033ea80b.png)

**Comment by wouterj** [comment]
This is almost identical to https://github.com/doctrine/rst-parser/pull/124 (but that was fixed in another place)

**Comment by nikophil** [comment]
thanks @wouterj for pointing this out :)

i've provided a fix on the parser https://github.com/doctrine/rst-parser/pull/135

**Comment by javiereguiluz** [comment]
Closing as fixed. Thanks!
