### ISSUE TITLE
Unsupported "strong" directive

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#50]
This file https://github.com/liip/LiipImagineBundle/blob/2.x/Resources/doc/filters/general.rst uses `:strong:` to make text bold:

```rst
Background Options
~~~~~~~~~~~~~~~~~~

:strong:`color:` ``string``
    Sets the background color HEX value. The default color is white (``#fff``).

:strong:`size:` ``int[]``
    Sets the generated background size as an integer array containing the dimensions
    as width and height values.
```

Sphinx supports it:

![image](https://user-images.githubusercontent.com/73419/109839793-c257fa80-7c47-11eb-9240-86090cbfe6f6.png)

But docs-builder doesn't:

![image](https://user-images.githubusercontent.com/73419/109839807-c6841800-7c47-11eb-90a2-80aa979a8977.png)

Question: should we implement this?

My opinion: if it's not too complicated, yes. Otherwise, "won't fix".

**Comment by wouterj** [comment]
The `:strong:` role is equal to `**...**`. I guess it's quite easy to implement the role, but I would also vote to use `**color**` in the LiipImagineBundle docs.

**Comment by javiereguiluz** [comment]
Yes, this could be a team-effort: ask Symfony bundles to please use @OskarStark's "DOCtor RST" for their docs ... and implement some rule in DOCtor to suggest using `**` instead of `:strong:` (same for other things that we might find).

**Comment by javiereguiluz** [comment]
Closing as "won't fix".

The LiipImagineBundle contents are being fixed in https://github.com/liip/LiipImagineBundle/pull/1361 and I've opened an issue in DOCtor-RST: https://github.com/OskarStark/doctor-rst/issues/931
