### ISSUE TITLE
Mark prompts differently in terminal/console blocks

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#68]
`code-block:: terminal` is highlighted like this:

![image](https://user-images.githubusercontent.com/73419/110931432-8b11d980-832a-11eb-88c6-6e9b09218ddd.png)

We need the "prompt" (`$` in Linux and macOS and `C:\>` in Windows) to be marked differently. This way we can apply different CSS styles to it and make it non-selectable by users (important when copying commands).

Today we do this using some ugly JS/CSS hacks ... but thanks to the new RST parser we could do this in PHP while building docs. It's similar to this -> https://github.com/weaverryan/docs-builder/pull/41/files

We could use `hljs-prompt` as the CSS class of this new element. Any volunteer to take care of this? Thanks!

**Comment by weaverryan** [comment]
Fixed by #78 

Too easy Javier 🥱 😉

**Comment by javiereguiluz** [comment]
😄   Thanks Ryan!
