### ISSUE TITLE
Globs in TOC trees seem to be dependent on the OS

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#72]
See https://github.com/weaverryan/docs-builder/pull/69#issuecomment-800065133 for details.

**Comment by weaverryan** [comment]
Will be fixed by https://github.com/doctrine/rst-parser/pull/141

**Comment by javiereguiluz** [comment]
Closing as fixed by https://github.com/doctrine/rst-parser/pull/141 Thanks!
