### ISSUE TITLE
The fjson file should keep the "parents" option

### ISSUE THREAD

**Issue by javiereguiluz** [weaverryan/docs-builder#74]
Sphinx describes the `parents` option as:

```
parents, prev and next:
    Information about related chapters in the TOC tree. Each relation is a
    dictionary with the keys link (HREF for the relation) and title (title
    of the related document, as HTML). parents is a list of relations,
    while prev and next are a single relation.
```

Source: https://www.sphinx-doc.org/en/1.0/builders.html#serialization-builder-details

-----

An example in practice:

This RST file from the Symfony Docs ->
https://github.com/symfony/symfony-docs/blob/5.x/contributing/code/bugs.rst

Is included in this `index.rst` from the section it belongs to:
https://github.com/symfony/symfony-docs/blob/5.x/contributing/code/index.rst

Which in turn is included in this `index.rst` from the main section:
https://github.com/symfony/symfony-docs/blob/5.x/contributing/index.rst

When the `*.fjson` is generated, it contains the following `parents`:

```json
"parents": [
    {"link": "../index.html", "title": "Contributing"},
    {"link": "index.html", "title": "Contributing Code"}
]
```

This is used in some parts of symfony.com to generate the breadcrumbs, so we'd need to re-add this option. I don't know if it's very complicated to do so or not 😐

**Comment by weaverryan** [comment]
Fixed in #76
