### ISSUE TITLE
"backed by" reference appears incomplete

### ISSUE THREAD

**Issue by jrushlow** [weaverryan/docs-builder#94]
Not sure if we're building the 5.3 docs up on production w/ docs builder yet - but if we are, I stumbled on:

![image](https://user-images.githubusercontent.com/40327885/113893869-6d069000-9795-11eb-91f0-6f03af1a97b5.png)

https://symfony.com/doc/5.3/reference/twig_reference.html

The "Backed By Jolicode" feels like its missing something.

**Comment by wouterj** [comment]
Hi! This has been reported in https://github.com/symfony/symfony-docs/issues/15196 (and if I'm correct, will be fixed after a deploy).

**Comment by jrushlow** [comment]
awesome! welp - we don't need this here then haha
